export default {
  flightList:{
    "A":[
        {
            "firstLetter":"A",
            "airportCode":"ADL",
            "airportName":"阿德莱德",
            "airportPy":"adelaide",
            "airportPyShort":"adld"
        },
        {
            "firstLetter":"A",
            "airportCode":"EDI",
            "airportName":"爱丁堡",
            "airportPy":"aidingbao",
            "airportPyShort":"adb"
        },
        {
            "firstLetter":"A",
            "airportCode":"AHL",
            "airportName":"Aishalton夏威夷",
            "airportPy":"aishaltonxiaweiyi",
            "airportPyShort":"aishaltonxwy"
        },
        {
            "firstLetter":"A",
            "airportCode":"ACC",
            "airportName":"阿克拉科托卡",
            "airportPy":"akelaketuoka",
            "airportPyShort":"aklktk"
        },
        {
            "firstLetter":"A",
            "airportCode":"AKL",
            "airportName":"奥克兰",
            "airportPy":"aokelan",
            "airportPyShort":"akl"
        },
        {
            "firstLetter":"A",
            "airportCode":"MFM",
            "airportName":"澳门",
            "airportPy":"aomen",
            "airportPyShort":"am"
        }
    ],
    "B":[
        {
            "firstLetter":"B",
            "airportCode":"SXF",
            "airportName":"柏林舍讷费尔德",
            "airportPy":"bailinshenefeierde",
            "airportPyShort":"blsnfed"
        },
        {
            "firstLetter":"B",
            "airportCode":"TXL",
            "airportName":"柏林泰格尔",
            "airportPy":"bailintaigeer",
            "airportPyShort":"bltge"
        },
        {
            "firstLetter":"B",
            "airportCode":"ORY",
            "airportName":"巴黎－奥利",
            "airportPy":"bali aoli",
            "airportPyShort":"bl al"
        },
        {
            "firstLetter":"B",
            "airportCode":"CDG",
            "airportName":"巴黎戴高乐",
            "airportPy":"balidaigaole",
            "airportPyShort":"bldgl"
        },
        {
            "firstLetter":"B",
            "airportCode":"BCN",
            "airportName":"巴塞罗那",
            "airportPy":"basailuona",
            "airportPyShort":"bsln"
        },
        {
            "firstLetter":"B",
            "airportCode":"BHX",
            "airportName":"伯明翰",
            "airportPy":"bominghan",
            "airportPyShort":"bmh"
        },
        {
            "firstLetter":"B",
            "airportCode":"BOS",
            "airportName":"波士顿",
            "airportPy":"boshidun",
            "airportPyShort":"bsd"
        },
        {
            "firstLetter":"B",
            "airportCode":"BUD",
            "airportName":"布达佩斯",
            "airportPy":"budapeisi",
            "airportPyShort":"bdps"
        },
        {
            "firstLetter":"B",
            "airportCode":"PRG",
            "airportName":"布拉格",
            "airportPy":"bulage",
            "airportPyShort":"blg"
        },
        {
            "firstLetter":"B",
            "airportCode":"BNE",
            "airportName":"布里斯班",
            "airportPy":"bulisiban",
            "airportPyShort":"blsb"
        },
        {
            "firstLetter":"B",
            "airportCode":"BRU",
            "airportName":"布鲁塞尔",
            "airportPy":"bulusaier",
            "airportPyShort":"blse"
        },
        {
            "firstLetter":"B",
            "airportCode":"EZE",
            "airportName":"布宜诺斯艾利斯埃塞萨皮斯塔里尼部长",
            "airportPy":"buyinuosiailisiaisaisapisitalinibuchang",
            "airportPyShort":"bynsalsasspstlnbc"
        }
    ],
    "D":[
        {
            "firstLetter":"D",
            "airportCode":"KIX",
            "airportName":"大阪关西",
            "airportPy":"dabanguanxi",
            "airportPyShort":"dbgx"
        },
        {
            "firstLetter":"D",
            "airportCode":"ITM",
            "airportName":"大阪伊丹",
            "airportPy":"dabanyidan",
            "airportPyShort":"dbyd"
        },
        {
            "firstLetter":"D",
            "airportCode":"DAR",
            "airportName":"达累斯萨拉姆尼雷尔",
            "airportPy":"daleisisalamunileier",
            "airportPyShort":"dlsslmnle"
        },
        {
            "firstLetter":"D",
            "airportCode":"DUR",
            "airportName":"德班",
            "airportPy":"deban",
            "airportPyShort":"db"
        },
        {
            "firstLetter":"D",
            "airportCode":"DPS",
            "airportName":"登巴萨巴厘岛",
            "airportPy":"dengbasabalidao",
            "airportPyShort":"dbsbld"
        },
        {
            "firstLetter":"D",
            "airportCode":"DXB",
            "airportName":"迪拜",
            "airportPy":"dibai",
            "airportPyShort":"db"
        },
        {
            "firstLetter":"D",
            "airportCode":"DTW",
            "airportName":"底特律大都会",
            "airportPy":"ditelvdaduhui",
            "airportPyShort":"dtlddh"
        },
        {
            "firstLetter":"D",
            "airportCode":"NRT",
            "airportName":"东京成田",
            "airportPy":"dongjingchengtian",
            "airportPyShort":"djct"
        },
        {
            "firstLetter":"D",
            "airportCode":"HND",
            "airportName":"东京羽田",
            "airportPy":"dongjingyutian",
            "airportPyShort":"djyt"
        },
        {
            "firstLetter":"D",
            "airportCode":"YYZ",
            "airportName":"多伦多皮尔逊",
            "airportPy":"duolunduopierxun",
            "airportPyShort":"dldpex"
        }
    ],
    "F":[
        {
            "firstLetter":"F",
            "airportCode":"FRA",
            "airportName":"法兰克福",
            "airportPy":"falankefu",
            "airportPyShort":"flkf"
        },
        {
            "firstLetter":"F",
            "airportCode":"FUK",
            "airportName":"福冈",
            "airportPy":"fugang",
            "airportPyShort":"fg"
        },
        {
            "firstLetter":"F",
            "airportCode":"PUS",
            "airportName":"釜山金海",
            "airportPy":"fushanjinhai",
            "airportPyShort":"fsjh"
        }
    ],
    "G":[
        {
            "firstLetter":"G",
            "airportCode":"KHH",
            "airportName":"高雄",
            "airportPy":"gaoxiong",
            "airportPyShort":"gx"
        },
        {
            "firstLetter":"G",
            "airportCode":"CPH",
            "airportName":"哥本哈根",
            "airportPy":"gebenhagen",
            "airportPyShort":"gbhg"
        }
    ],
    "H":[
        {
            "firstLetter":"H",
            "airportCode":"HRE",
            "airportName":"哈拉雷",
            "airportPy":"halalei",
            "airportPyShort":"hll"
        },
        {
            "firstLetter":"H",
            "airportCode":"HAM",
            "airportName":"汉堡",
            "airportPy":"hanbao",
            "airportPyShort":"hb"
        },
        {
            "firstLetter":"H",
            "airportCode":"HEL",
            "airportName":"赫尔辛基",
            "airportPy":"heerxinji",
            "airportPyShort":"hexj"
        },
        {
            "firstLetter":"H",
            "airportCode":"AMS",
            "airportName":"荷兰阿姆斯特丹斯史基浦(西霍普)",
            "airportPy":"helanamusitedansishijipu xihuopu",
            "airportPyShort":"hlamstdssjp xhp"
        },
        {
            "firstLetter":"H",
            "airportCode":"HAN",
            "airportName":"河内内拜",
            "airportPy":"heneineibai",
            "airportPyShort":"hnnb"
        },
        {
            "firstLetter":"H",
            "airportCode":"IAD",
            "airportName":"华盛顿杜勒斯",
            "airportPy":"huashengdundulesi",
            "airportPyShort":"hsddls"
        },
        {
            "firstLetter":"H",
            "airportCode":"WLG",
            "airportName":"惠灵顿",
            "airportPy":"huilingdun",
            "airportPyShort":"hld"
        },
        {
            "firstLetter":"H",
            "airportCode":"SGN",
            "airportName":"胡志明市新山一",
            "airportPy":"huzhimingshixinshanyi",
            "airportPyShort":"hzmsxsy"
        }
    ],
    "J":[
        {
            "firstLetter":"J",
            "airportCode":"KTM",
            "airportName":"加德满都",
            "airportPy":"jiademandu",
            "airportPyShort":"jdmd"
        },
        {
            "firstLetter":"J",
            "airportCode":"IEV",
            "airportName":"基辅",
            "airportPy":"jifu",
            "airportPyShort":"jf"
        },
        {
            "firstLetter":"J",
            "airportCode":"KUL",
            "airportName":"吉隆坡",
            "airportPy":"jilongpo",
            "airportPyShort":"jlp"
        },
        {
            "firstLetter":"J",
            "airportCode":"PNH",
            "airportName":"金边",
            "airportPy":"jinbian",
            "airportPyShort":"jb"
        },
        {
            "firstLetter":"J",
            "airportCode":"SFO",
            "airportName":"旧金山",
            "airportPy":"jiujinshan",
            "airportPyShort":"jjs"
        },
        {
            "firstLetter":"J",
            "airportCode":"CJU",
            "airportName":"济州岛济州",
            "airportPy":"jizhoudaojizhou",
            "airportPyShort":"jzdjz"
        }
    ],
    "K":[
        {
            "firstLetter":"K",
            "airportCode":"YYC",
            "airportName":"卡尔加里CALGARY",
            "airportPy":"kaerjialicalgary",
            "airportPyShort":"kejlcalgary"
        },
        {
            "firstLetter":"K",
            "airportCode":"CAI",
            "airportName":"开罗",
            "airportPy":"kailuo",
            "airportPyShort":"kl"
        },
        {
            "firstLetter":"K",
            "airportCode":"CPT",
            "airportName":"开普敦开普顿",
            "airportPy":"kaipudunkaipudun",
            "airportPyShort":"kpdkpd"
        },
        {
            "firstLetter":"K",
            "airportCode":"CBR",
            "airportName":"堪培拉",
            "airportPy":"kanpeila",
            "airportPyShort":"kpl"
        }
    ],
    "L":[
        {
            "firstLetter":"L",
            "airportCode":"LAS",
            "airportName":"拉斯维加斯麦卡伦",
            "airportPy":"lasiweijiasimaikalun",
            "airportPyShort":"lswjsmkl"
        },
        {
            "firstLetter":"L",
            "airportCode":"LGW",
            "airportName":"伦敦盖特威克",
            "airportPy":"lundungaiteweike",
            "airportPyShort":"ldgtwk"
        },
        {
            "firstLetter":"L",
            "airportCode":"LHR",
            "airportName":"伦敦希思罗",
            "airportPy":"lundunxisiluo",
            "airportPyShort":"ldxsl"
        },
        {
            "firstLetter":"L",
            "airportCode":"LAD",
            "airportName":"罗安达二月四日",
            "airportPy":"luoandaeryuesiri",
            "airportPyShort":"ladeysr"
        },
        {
            "firstLetter":"L",
            "airportCode":"FCO",
            "airportName":"罗马菲乌米奇诺",
            "airportPy":"luomafeiwumiqinuo",
            "airportPyShort":"lmfwmqn"
        },
        {
            "firstLetter":"L",
            "airportCode":"LAX",
            "airportName":"洛杉矶",
            "airportPy":"luoshanji",
            "airportPyShort":"lsj"
        }
    ],
    "M":[
        {
            "firstLetter":"M",
            "airportCode":"MAD",
            "airportName":"马德里",
            "airportPy":"madeli",
            "airportPyShort":"mdl"
        },
        {
            "firstLetter":"M",
            "airportCode":"MLE",
            "airportName":"马累",
            "airportPy":"malei",
            "airportPyShort":"ml"
        },
        {
            "firstLetter":"M",
            "airportCode":"MAN",
            "airportName":"曼彻斯特",
            "airportPy":"manchesite",
            "airportPyShort":"mcst"
        },
        {
            "firstLetter":"M",
            "airportCode":"BKK",
            "airportName":"曼谷(素万那普)",
            "airportPy":"mangu suwannapu",
            "airportPyShort":"mg swnp"
        },
        {
            "firstLetter":"M",
            "airportCode":"MNL",
            "airportName":"马尼拉",
            "airportPy":"manila",
            "airportPyShort":"mnl"
        },
        {
            "firstLetter":"M",
            "airportCode":"MRU",
            "airportName":"毛里求斯",
            "airportPy":"maoliqiusi",
            "airportPyShort":"mlqs"
        },
        {
            "firstLetter":"M",
            "airportCode":"BOM",
            "airportName":"孟买",
            "airportPy":"mengmai",
            "airportPyShort":"mm"
        },
        {
            "firstLetter":"M",
            "airportCode":"YUL",
            "airportName":"蒙特利尔特鲁多",
            "airportPy":"mengtelierteluduo",
            "airportPyShort":"mtletld"
        },
        {
            "firstLetter":"M",
            "airportCode":"LIN",
            "airportName":"米兰利纳特",
            "airportPy":"milanlinate",
            "airportPyShort":"mllnt"
        },
        {
            "firstLetter":"M",
            "airportCode":"MXP",
            "airportName":"米兰马尔本萨",
            "airportPy":"milanmaerbensa",
            "airportPyShort":"mlmebs"
        },
        {
            "firstLetter":"M",
            "airportCode":"NGO",
            "airportName":"名古屋中部/新特丽亚",
            "airportPy":"mingguwuzhongbu xinteliya",
            "airportPyShort":"mgwzb xtly"
        },
        {
            "firstLetter":"M",
            "airportCode":"MEL",
            "airportName":"墨尔本",
            "airportPy":"moerben",
            "airportPyShort":"meb"
        },
        {
            "firstLetter":"M",
            "airportCode":"DME",
            "airportName":"莫斯科多莫杰多沃",
            "airportPy":"mosikeduomojieduowo",
            "airportPyShort":"mskdmjdw"
        },
        {
            "firstLetter":"M",
            "airportCode":"VKO",
            "airportName":"莫斯科伏努科沃",
            "airportPy":"mosikefunukewo",
            "airportPyShort":"mskfnkw"
        },
        {
            "firstLetter":"M",
            "airportCode":"SVO",
            "airportName":"莫斯科谢诺梅杰沃",
            "airportPy":"mosikexienuomeijiewo",
            "airportPyShort":"mskxnmjw"
        },
        {
            "firstLetter":"M",
            "airportCode":"MEX",
            "airportName":"墨西哥城",
            "airportPy":"moxigecheng",
            "airportPyShort":"mxgc"
        },
        {
            "firstLetter":"M",
            "airportCode":"MUC",
            "airportName":"慕尼黑",
            "airportPy":"munihei",
            "airportPyShort":"mnh"
        }
    ],
    "N":[
        {
            "firstLetter":"N",
            "airportCode":"NBO",
            "airportName":"内罗毕乔莫·肯雅塔",
            "airportPy":"neiluobiqiaomo kenyata",
            "airportPyShort":"nlbqm kyt"
        },
        {
            "firstLetter":"N",
            "airportCode":"NTL",
            "airportName":"纽卡斯尔威廉斯敦",
            "airportPy":"niukasierweiliansidun",
            "airportPyShort":"nksewlsd"
        },
        {
            "firstLetter":"N",
            "airportCode":"JFK",
            "airportName":"纽约肯尼迪",
            "airportPy":"niuyuekennidi",
            "airportPyShort":"nyknd"
        },
        {
            "firstLetter":"N",
            "airportCode":"LGA",
            "airportName":"纽约拉瓜迪亚",
            "airportPy":"niuyuelaguadiya",
            "airportPyShort":"nylgdy"
        }
    ],
    "P":[
        {
            "firstLetter":"P",
            "airportCode":"PER",
            "airportName":"珀斯",
            "airportPy":"posi",
            "airportPyShort":"ps"
        },
        {
            "firstLetter":"P",
            "airportCode":"HKT",
            "airportName":"普吉岛普吉",
            "airportPy":"pujidaopuji",
            "airportPyShort":"pjdpj"
        }
    ],
    "R":[
        {
            "firstLetter":"R",
            "airportCode":"GVA",
            "airportName":"日内瓦",
            "airportPy":"rineiwa",
            "airportPyShort":"rnw"
        }
    ],
    "S":[
        {
            "firstLetter":"S",
            "airportCode":"SPN",
            "airportName":"塞班",
            "airportPy":"saiban",
            "airportPyShort":"sb"
        },
        {
            "firstLetter":"S",
            "airportCode":"GRU",
            "airportName":"圣保罗",
            "airportPy":"shengbaoluo",
            "airportPyShort":"sbl"
        },
        {
            "firstLetter":"S",
            "airportCode":"LED",
            "airportName":"圣彼得堡",
            "airportPy":"shengbidebao",
            "airportPyShort":"sbdb"
        },
        {
            "firstLetter":"S",
            "airportCode":"GMP",
            "airportName":"首尔金浦",
            "airportPy":"shouerjinpu",
            "airportPyShort":"sejp"
        },
        {
            "firstLetter":"S",
            "airportCode":"ICN",
            "airportName":"首尔仁川",
            "airportPy":"shouerrenchuan",
            "airportPyShort":"serc"
        },
        {
            "firstLetter":"S",
            "airportCode":"ARN",
            "airportName":"斯德哥尔摩",
            "airportPy":"sidegeermo",
            "airportPyShort":"sdgem"
        },
        {
            "firstLetter":"S",
            "airportCode":"ZRH",
            "airportName":"苏黎世",
            "airportPy":"sulishi",
            "airportPyShort":"sls"
        }
    ],
    "T":[
        {
            "firstLetter":"T",
            "airportCode":"TPE,TSA",
            "airportName":"台北",
            "airportPy":"taibei",
            "airportPyShort":"tb"
        },
        {
            "firstLetter":"T",
            "airportCode":"TSA",
            "airportName":"台北松山",
            "airportPy":"taibeisongshan",
            "airportPyShort":"tbss"
        },
        {
            "firstLetter":"T",
            "airportCode":"TPE",
            "airportName":"台北桃园",
            "airportPy":"taibeitaoyuan",
            "airportPyShort":"tbty"
        }
    ],
    "W":[
        {
            "firstLetter":"W",
            "airportCode":"YVR",
            "airportName":"温哥华",
            "airportPy":"wengehua",
            "airportPyShort":"wgh"
        },
        {
            "firstLetter":"W",
            "airportCode":"YOW",
            "airportName":"渥太华",
            "airportPy":"wotaihua",
            "airportPyShort":"wth"
        },
        {
            "firstLetter":"W",
            "airportCode":"ULN",
            "airportName":"乌兰巴托",
            "airportPy":"wulanbatuo",
            "airportPyShort":"wlbt"
        }
    ],
    "X":[
        {
            "firstLetter":"X",
            "airportCode":"HKG",
            "airportName":"香港赤鱲角",
            "airportPy":"xianggangchiliejiao",
            "airportPyShort":"xgclj"
        },
        {
            "firstLetter":"X",
            "airportCode":"DEL",
            "airportName":"新德里德里",
            "airportPy":"xindelideli",
            "airportPyShort":"xdldl"
        },
        {
            "firstLetter":"X",
            "airportCode":"SYD",
            "airportName":"悉尼金斯福德·史密斯",
            "airportPy":"xinijinsifude shimisi",
            "airportPyShort":"xnjsfd sms"
        },
        {
            "firstLetter":"X",
            "airportCode":"SIN",
            "airportName":"新加坡樟宜",
            "airportPy":"xinjiapozhangyi",
            "airportPyShort":"xjpzy"
        },
        {
            "firstLetter":"X",
            "airportCode":"IAH",
            "airportName":"休斯敦",
            "airportPy":"xiusidun",
            "airportPyShort":"xsd"
        },
        {
            "firstLetter":"X",
            "airportCode":"SEA",
            "airportName":"西雅图塔科马",
            "airportPy":"xiyatutakema",
            "airportPyShort":"xyttkm"
        }
    ],
    "Y":[
        {
            "firstLetter":"Y",
            "airportCode":"ADD",
            "airportName":"亚的斯亚贝巴博乐",
            "airportPy":"yadesiyabeibabole",
            "airportPyShort":"ydsybbbl"
        },
        {
            "firstLetter":"Y",
            "airportCode":"ATH",
            "airportName":"雅典",
            "airportPy":"yadian",
            "airportPyShort":"yd"
        },
        {
            "firstLetter":"Y",
            "airportCode":"CGK",
            "airportName":"雅加达苏加诺-哈达",
            "airportPy":"yajiadasujianuo hada",
            "airportPyShort":"yjdsjn hd"
        },
        {
            "firstLetter":"Y",
            "airportCode":"IST",
            "airportName":"伊斯坦布尔阿塔图尔克",
            "airportPy":"yisitanbueratatuerke",
            "airportPyShort":"ystbeattek"
        },
        {
            "firstLetter":"Y",
            "airportCode":"JNB",
            "airportName":"约翰内斯堡",
            "airportPy":"yuehanneisibao",
            "airportPyShort":"yhnsb"
        }
    ],
    "Z":[
        {
            "firstLetter":"Z",
            "airportCode":"ORD",
            "airportName":"芝加哥奥黑尔",
            "airportPy":"zhijiageaoheier",
            "airportPyShort":"zjgahe"
        }
    ]
}
}
