export default {
  flightList:{
    "A":[
        {
            "firstLetter":"A",
            "airportCode":"AHJ",
            "airportName":"阿坝红原",
            "airportPy":"abahongyuan",
            "airportPyShort":"abhy"
        },
        {
            "firstLetter":"A",
            "airportCode":"YIE",
            "airportName":"阿尔山伊尔施",
            "airportPy":"aershanyiershi",
            "airportPyShort":"aesyes"
        },
        {
            "firstLetter":"A",
            "airportCode":"AKU",
            "airportName":"阿克苏温宿",
            "airportPy":"akesuwensu",
            "airportPyShort":"aksws"
        },
        {
            "firstLetter":"A",
            "airportCode":"AAT",
            "airportName":"阿勒泰",
            "airportPy":"aletai",
            "airportPyShort":"alt"
        },
        {
            "firstLetter":"A",
            "airportCode":"NGQ",
            "airportName":"阿里昆莎",
            "airportPy":"alikunsha",
            "airportPyShort":"alks"
        },
        {
            "firstLetter":"A",
            "airportCode":"AKA",
            "airportName":"安康",
            "airportPy":"ankang",
            "airportPyShort":"ak"
        },
        {
            "firstLetter":"A",
            "airportCode":"AQG",
            "airportName":"安庆天柱山",
            "airportPy":"anqingtianzhushan",
            "airportPyShort":"aqtzs"
        },
        {
            "firstLetter":"A",
            "airportCode":"AOG",
            "airportName":"鞍山腾鳌",
            "airportPy":"anshantengao",
            "airportPyShort":"asta"
        },
        {
            "firstLetter":"A",
            "airportCode":"AVA",
            "airportName":"安顺黄果树",
            "airportPy":"anshunhuangguoshu",
            "airportPyShort":"ashgs"
        },
        {
            "firstLetter":"A",
            "airportCode":"AYN",
            "airportName":"安阳北郊",
            "airportPy":"anyangbeijiao",
            "airportPyShort":"aybj"
        },
        {
            "firstLetter":"A",
            "airportCode":"MFM",
            "airportName":"澳门",
            "airportPy":"aomen",
            "airportPyShort":"am"
        }
    ],
    "B":[
        {
            "firstLetter":"B",
            "airportCode":"AEB",
            "airportName":"百色田阳",
            "airportPy":"baisetianyang",
            "airportPyShort":"bsty"
        },
        {
            "firstLetter":"B",
            "airportCode":"BSD",
            "airportName":"保山云瑞",
            "airportPy":"baoshanyunrui",
            "airportPyShort":"bsyr"
        },
        {
            "firstLetter":"B",
            "airportCode":"BAV",
            "airportName":"包头二里半",
            "airportPy":"baotouerliban",
            "airportPyShort":"btelb"
        },
        {
            "firstLetter":"B",
            "airportCode":"RLK",
            "airportName":"巴彦淖尔天吉泰",
            "airportPy":"bayannaoertianjitai",
            "airportPyShort":"bynetjt"
        },
        {
            "firstLetter":"B",
            "airportCode":"MFK",
            "airportName":"北竿",
            "airportPy":"beigan",
            "airportPyShort":"bg"
        },
        {
            "firstLetter":"B",
            "airportCode":"BHY",
            "airportName":"北海福成",
            "airportPy":"beihaifucheng",
            "airportPyShort":"bhfc"
        },
        {
            "firstLetter":"B",
            "airportCode":"PEK,NAY",
            "airportName":"北京",
            "airportPy":"beijing",
            "airportPyShort":"bj"
        },
        {
            "firstLetter":"B",
            "airportCode":"NAY",
            "airportName":"北京南苑",
            "airportPy":"beijingnanyuan",
            "airportPyShort":"bjny"
        },
        {
            "firstLetter":"B",
            "airportCode":"PEK",
            "airportName":"北京首都",
            "airportPy":"beijingshoudu",
            "airportPyShort":"bjsd"
        },
        {
            "firstLetter":"B",
            "airportCode":"BFJ",
            "airportName":"毕节飞雄",
            "airportPy":"bijiefeixiong",
            "airportPyShort":"bjfx"
        },
        {
            "firstLetter":"B",
            "airportCode":"BPL",
            "airportName":"博乐阿拉山口",
            "airportPy":"bolealashankou",
            "airportPyShort":"blalsk"
        }
    ],
    "C":[
        {
            "firstLetter":"C",
            "airportCode":"NBS",
            "airportName":"长白山",
            "airportPy":"changbaishan",
            "airportPyShort":"cbs"
        },
        {
            "firstLetter":"C",
            "airportCode":"CGQ",
            "airportName":"长春龙嘉",
            "airportPy":"changchunlongjia",
            "airportPyShort":"cclj"
        },
        {
            "firstLetter":"C",
            "airportCode":"CGD",
            "airportName":"常德桃花源",
            "airportPy":"changdetaohuayuan",
            "airportPyShort":"cdthy"
        },
        {
            "firstLetter":"C",
            "airportCode":"BPX",
            "airportName":"昌都邦达",
            "airportPy":"changdubangda",
            "airportPyShort":"cdbd"
        },
        {
            "firstLetter":"C",
            "airportCode":"CSX",
            "airportName":"长沙黄花",
            "airportPy":"changshahuanghua",
            "airportPyShort":"cshh"
        },
        {
            "firstLetter":"C",
            "airportCode":"CIH",
            "airportName":"长治王村",
            "airportPy":"changzhiwangcun",
            "airportPyShort":"czwc"
        },
        {
            "firstLetter":"C",
            "airportCode":"CZX",
            "airportName":"常州奔牛",
            "airportPy":"changzhoubenniu",
            "airportPyShort":"czbn"
        },
        {
            "firstLetter":"C",
            "airportCode":"CHG",
            "airportName":"朝阳",
            "airportPy":"chaoyang",
            "airportPyShort":"cy"
        },
        {
            "firstLetter":"C",
            "airportCode":"CTU",
            "airportName":"成都双流",
            "airportPy":"chengdushuangliu",
            "airportPyShort":"cdsl"
        },
        {
            "firstLetter":"C",
            "airportCode":"CIF",
            "airportName":"赤峰玉龙",
            "airportPy":"chifengyulong",
            "airportPyShort":"cfyl"
        },
        {
            "firstLetter":"C",
            "airportCode":"JUH",
            "airportName":"池州九华山",
            "airportPy":"chizhoujiuhuashan",
            "airportPyShort":"czjhs"
        },
        {
            "firstLetter":"C",
            "airportCode":"CKG",
            "airportName":"重庆江北",
            "airportPy":"chongqingjiangbei",
            "airportPyShort":"cqjb"
        }
    ],
    "D":[
        {
            "firstLetter":"D",
            "airportCode":"DLC",
            "airportName":"大连周水子",
            "airportPy":"dalian",
            "airportPyShort":"dl"
        },
        {
            "firstLetter":"D",
            "airportCode":"DLU",
            "airportName":"大理荒草坝",
            "airportPy":"dalihuangcaoba",
            "airportPyShort":"dlhcb"
        },
        {
            "firstLetter":"D",
            "airportCode":"DDG",
            "airportName":"丹东浪头",
            "airportPy":"dandonglangtou",
            "airportPyShort":"ddlt"
        },
        {
            "firstLetter":"D",
            "airportCode":"DCY",
            "airportName":"稻城亚丁",
            "airportPy":"daochengyading",
            "airportPyShort":"dcyd"
        },
        {
            "firstLetter":"D",
            "airportCode":"DQA",
            "airportName":"大庆萨尔图",
            "airportPy":"daqingsaertu",
            "airportPyShort":"dqset"
        },
        {
            "firstLetter":"D",
            "airportCode":"DAT",
            "airportName":"大同云冈",
            "airportPy":"datongyungang",
            "airportPyShort":"dtyg"
        },
        {
            "firstLetter":"D",
            "airportCode":"DAX",
            "airportName":"达州河市",
            "airportPy":"dazhouheshi",
            "airportPyShort":"dzhs"
        },
        {
            "firstLetter":"D",
            "airportCode":"HXD",
            "airportName":"德令哈",
            "airportPy":"delingha",
            "airportPyShort":"dlh"
        },
        {
            "firstLetter":"D",
            "airportCode":"DIG",
            "airportName":"迪庆香格里拉",
            "airportPy":"diqingxianggelila",
            "airportPyShort":"dqxgll"
        },
        {
            "firstLetter":"D",
            "airportCode":"DOY",
            "airportName":"东营胜利",
            "airportPy":"dongyingshengli",
            "airportPyShort":"dysl"
        },
        {
            "firstLetter":"D",
            "airportCode":"DNH",
            "airportName":"敦煌",
            "airportPy":"dunhuang",
            "airportPyShort":"dh"
        }
    ],
    "E":[
        {
            "firstLetter":"E",
            "airportCode":"DSN",
            "airportName":"鄂尔多斯伊金霍洛",
            "airportPy":"eerduosiyijinhuoluo",
            "airportPyShort":"eedsyjhl"
        },
        {
            "firstLetter":"E",
            "airportCode":"EJN",
            "airportName":"额济纳旗桃来",
            "airportPy":"ejinaqitaolai",
            "airportPyShort":"ejnqtl"
        },
        {
            "firstLetter":"E",
            "airportCode":"ENH",
            "airportName":"恩施许家坪",
            "airportPy":"enshixujiaping",
            "airportPyShort":"esxjp"
        },
        {
            "firstLetter":"E",
            "airportCode":"ERL",
            "airportName":"二连浩特赛乌素",
            "airportPy":"erlianhaotesaiwusu",
            "airportPyShort":"elhtsws"
        }
    ],
    "F":[
        {
            "firstLetter":"F",
            "airportCode":"FUO",
            "airportName":"佛山沙堤",
            "airportPy":"foshanshadi",
            "airportPyShort":"fssd"
        },
        {
            "firstLetter":"F",
            "airportCode":"LCX",
            "airportName":"福建龙岩冠豸山",
            "airportPy":"fujianlongyanguanzhishan",
            "airportPyShort":"fjlygzs"
        },
        {
            "firstLetter":"F",
            "airportCode":"FUG",
            "airportName":"阜阳西关",
            "airportPy":"fuyangxiguan",
            "airportPyShort":"fyxg"
        },
        {
            "firstLetter":"F",
            "airportCode":"FYJ",
            "airportName":"抚远东极",
            "airportPy":"fuyuandongji",
            "airportPyShort":"fydj"
        },
        {
            "firstLetter":"F",
            "airportCode":"FYN",
            "airportName":"富蕴",
            "airportPy":"fuyun",
            "airportPyShort":"fy"
        },
        {
            "firstLetter":"F",
            "airportCode":"FOC",
            "airportName":"福州长乐",
            "airportPy":"fuzhouchangle",
            "airportPyShort":"fzcl"
        }
    ],
    "G":[
        {
            "firstLetter":"G",
            "airportCode":"GXH",
            "airportName":"甘南夏河",
            "airportPy":"gannanxiahe",
            "airportPyShort":"gnxh"
        },
        {
            "firstLetter":"G",
            "airportCode":"KOW",
            "airportName":"赣州黄金",
            "airportPy":"ganzhouhuangjin",
            "airportPyShort":"gzhj"
        },
        {
            "firstLetter":"G",
            "airportCode":"KHH",
            "airportName":"高雄",
            "airportPy":"gaoxiong",
            "airportPyShort":"gx"
        },
        {
            "firstLetter":"G",
            "airportCode":"GOQ",
            "airportName":"格尔木",
            "airportPy":"geermu",
            "airportPyShort":"gem"
        },
        {
            "firstLetter":"G",
            "airportCode":"GYS",
            "airportName":"广元盘龙",
            "airportPy":"guangyuanpanlong",
            "airportPyShort":"gypl"
        },
        {
            "firstLetter":"G",
            "airportCode":"CAN",
            "airportName":"广州白云",
            "airportPy":"guangzhoubaiyun",
            "airportPyShort":"gzby"
        },
        {
            "firstLetter":"G",
            "airportCode":"KWL",
            "airportName":"桂林两江",
            "airportPy":"guilinliangjiang",
            "airportPyShort":"gllj"
        },
        {
            "firstLetter":"G",
            "airportCode":"KWE",
            "airportName":"贵阳龙洞堡",
            "airportPy":"guiyanglongdongbao",
            "airportPyShort":"gyldb"
        },
        {
            "firstLetter":"G",
            "airportCode":"GYU",
            "airportName":"固原六盘山",
            "airportPy":"guyuanliupanshan",
            "airportPyShort":"gylps"
        }
    ],
    "H":[
        {
            "firstLetter":"H",
            "airportCode":"HRB",
            "airportName":"哈尔滨太平",
            "airportPy":"haerbintaiping",
            "airportPyShort":"hebtp"
        },
        {
            "firstLetter":"H",
            "airportCode":"HAK",
            "airportName":"海口美兰",
            "airportPy":"haikoumeilan",
            "airportPyShort":"hkml"
        },
        {
            "firstLetter":"H",
            "airportCode":"HLD",
            "airportName":"海拉尔东山",
            "airportPy":"hailaerdongshan",
            "airportPyShort":"hleds"
        },
        {
            "firstLetter":"H",
            "airportCode":"HMI",
            "airportName":"哈密",
            "airportPy":"hami",
            "airportPyShort":"hm"
        },
        {
            "firstLetter":"H",
            "airportCode":"HDG",
            "airportName":"邯郸",
            "airportPy":"handan",
            "airportPyShort":"hd"
        },
        {
            "firstLetter":"H",
            "airportCode":"HGH",
            "airportName":"杭州萧山",
            "airportPy":"hangzhouxiaoshan",
            "airportPyShort":"hzxs"
        },
        {
            "firstLetter":"H",
            "airportCode":"HZG",
            "airportName":"汉中城固",
            "airportPy":"hanzhongchenggu",
            "airportPyShort":"hzcg"
        },
        {
            "firstLetter":"H",
            "airportCode":"HCJ",
            "airportName":"河池金城江",
            "airportPy":"hechijinchengjiang",
            "airportPyShort":"hcjcj"
        },
        {
            "firstLetter":"H",
            "airportCode":"HFE",
            "airportName":"合肥新桥",
            "airportPy":"hefeixinqiao",
            "airportPyShort":"hfxq"
        },
        {
            "firstLetter":"H",
            "airportCode":"HEK",
            "airportName":"黑河",
            "airportPy":"heihe",
            "airportPyShort":"hh"
        },
        {
            "firstLetter":"H",
            "airportCode":"HCN",
            "airportName":"恒春五里亭",
            "airportPy":"hengchunwuliting",
            "airportPyShort":"hcwlt"
        },
        {
            "firstLetter":"H",
            "airportCode":"HNY",
            "airportName":"衡阳南岳",
            "airportPy":"hengyangnanyue",
            "airportPyShort":"hyny"
        },
        {
            "firstLetter":"H",
            "airportCode":"HTN",
            "airportName":"和田",
            "airportPy":"hetian",
            "airportPyShort":"ht"
        },
        {
            "firstLetter":"H",
            "airportCode":"HSZ",
            "airportName":"Hsinchu",
            "airportPy":"hsinchu",
            "airportPyShort":"hsinchu"
        },
        {
            "firstLetter":"H",
            "airportCode":"HIA",
            "airportName":"淮安涟水",
            "airportPy":"huaianlianshui",
            "airportPyShort":"hals"
        },
        {
            "firstLetter":"H",
            "airportCode":"HJJ",
            "airportName":"怀化芷江",
            "airportPy":"huaihuazhijiang",
            "airportPyShort":"hhzj"
        },
        {
            "firstLetter":"H",
            "airportCode":"HUN",
            "airportName":"花莲",
            "airportPy":"hualian",
            "airportPyShort":"hl"
        },
        {
            "firstLetter":"H",
            "airportCode":"TXN",
            "airportName":"黄山屯溪",
            "airportPy":"huangshantunxi",
            "airportPyShort":"hstx"
        },
        {
            "firstLetter":"H",
            "airportCode":"HTT",
            "airportName":"花土沟",
            "airportPy":"huatugou",
            "airportPyShort":"htg"
        },
        {
            "firstLetter":"H",
            "airportCode":"HET",
            "airportName":"呼和浩特白塔",
            "airportPy":"huhehaotebaita",
            "airportPyShort":"hhhtbt"
        },
        {
            "firstLetter":"H",
            "airportCode":"HUZ",
            "airportName":"惠州平潭",
            "airportPy":"huizhoupingtan",
            "airportPyShort":"hzpt"
        }
    ],
    "J":[
        {
            "firstLetter":"J",
            "airportCode":"JGD",
            "airportName":"加格达奇嘎仙",
            "airportPy":"jiagedaqigaxian",
            "airportPyShort":"jgdqgx"
        },
        {
            "firstLetter":"J",
            "airportCode":"JMU",
            "airportName":"佳木斯",
            "airportPy":"jiamusi",
            "airportPyShort":"jms"
        },
        {
            "firstLetter":"J",
            "airportCode":"CYI",
            "airportName":"嘉义",
            "airportPy":"jiayi",
            "airportPyShort":"jy"
        },
        {
            "firstLetter":"J",
            "airportCode":"JGN",
            "airportName":"嘉峪关",
            "airportPy":"jiayuguan",
            "airportPyShort":"jyg"
        },
        {
            "firstLetter":"J",
            "airportCode":"SWA",
            "airportName":"揭阳潮汕",
            "airportPy":"jieyangchaoshan",
            "airportPyShort":"jycs"
        },
        {
            "firstLetter":"J",
            "airportCode":"JIL",
            "airportName":"吉林二台子",
            "airportPy":"jilinertaizi",
            "airportPyShort":"jletz"
        },
        {
            "firstLetter":"J",
            "airportCode":"TNA",
            "airportName":"济南遥墙",
            "airportPy":"jinanyaoqiang",
            "airportPyShort":"jnyq"
        },
        {
            "firstLetter":"J",
            "airportCode":"JIC",
            "airportName":"金昌金川",
            "airportPy":"jinchangjinchuan",
            "airportPyShort":"jcjc"
        },
        {
            "firstLetter":"J",
            "airportCode":"JDZ",
            "airportName":"景德镇罗家",
            "airportPy":"jingdezhenluojia",
            "airportPyShort":"jdzlj"
        },
        {
            "firstLetter":"J",
            "airportCode":"JGS",
            "airportName":"井冈山",
            "airportPy":"jinggangshan",
            "airportPyShort":"jgs"
        },
        {
            "firstLetter":"J",
            "airportCode":"JNG",
            "airportName":"济宁曲阜",
            "airportPy":"jiningqufu",
            "airportPyShort":"jnqf"
        },
        {
            "firstLetter":"J",
            "airportCode":"JNZ",
            "airportName":"锦州湾",
            "airportPy":"jinzhouwan",
            "airportPyShort":"jzw"
        },
        {
            "firstLetter":"J",
            "airportCode":"JIU",
            "airportName":"九江庐山",
            "airportPy":"jiujianglushan",
            "airportPyShort":"jjls"
        },
        {
            "firstLetter":"J",
            "airportCode":"JZH",
            "airportName":"九寨沟黄龙",
            "airportPy":"jiuzhaigouhuanglong",
            "airportPyShort":"jzghl"
        },
        {
            "firstLetter":"J",
            "airportCode":"JXA",
            "airportName":"鸡西兴凯湖",
            "airportPy":"jixixingkaihu",
            "airportPyShort":"jxxkh"
        }
    ],
    "K":[
        {
            "firstLetter":"K",
            "airportCode":"KJH",
            "airportName":"凯里黄平",
            "airportPy":"kailihuangping",
            "airportPyShort":"klhp"
        },
        {
            "firstLetter":"K",
            "airportCode":"KJI",
            "airportName":"喀纳斯布尔津",
            "airportPy":"kanasibuerjin",
            "airportPyShort":"knsbej"
        },
        {
            "firstLetter":"K",
            "airportCode":"KGT",
            "airportName":"康定",
            "airportPy":"kangding",
            "airportPyShort":"kd"
        },
        {
            "firstLetter":"K",
            "airportCode":"KHG",
            "airportName":"喀什",
            "airportPy":"kashi",
            "airportPyShort":"ks"
        },
        {
            "firstLetter":"K",
            "airportCode":"KRY",
            "airportName":"克拉玛依",
            "airportPy":"kelamayi",
            "airportPyShort":"klmy"
        },
        {
            "firstLetter":"K",
            "airportCode":"KCA",
            "airportName":"库车龟兹",
            "airportPy":"kucheguizi",
            "airportPyShort":"kcgz"
        },
        {
            "firstLetter":"K",
            "airportCode":"KRL",
            "airportName":"库尔勒",
            "airportPy":"kuerle",
            "airportPyShort":"kel"
        },
        {
            "firstLetter":"K",
            "airportCode":"KMG",
            "airportName":"昆明长水",
            "airportPy":"kunmingchangshui",
            "airportPyShort":"kmcs"
        }
    ],
    "L":[
        {
            "firstLetter":"L",
            "airportCode":"LHW",
            "airportName":"兰州中川",
            "airportPy":"lanzhouzhongchuan",
            "airportPyShort":"lzzc"
        },
        {
            "firstLetter":"L",
            "airportCode":"LXA",
            "airportName":"拉萨贡嘎",
            "airportPy":"lasagongga",
            "airportPyShort":"lsgg"
        },
        {
            "firstLetter":"L",
            "airportCode":"LYG",
            "airportName":"连云港白塔埠",
            "airportPy":"lianyungangbaitabu",
            "airportPyShort":"lygbtb"
        },
        {
            "firstLetter":"L",
            "airportCode":"LLB",
            "airportName":"荔波",
            "airportPy":"libo",
            "airportPyShort":"lb"
        },
        {
            "firstLetter":"L",
            "airportCode":"LJG",
            "airportName":"丽江三义",
            "airportPy":"lijiangsanyi",
            "airportPyShort":"ljsy"
        },
        {
            "firstLetter":"L",
            "airportCode":"LNJ",
            "airportName":"临沧博尚",
            "airportPy":"lincangboshang",
            "airportPyShort":"lcbs"
        },
        {
            "firstLetter":"L",
            "airportCode":"LFQ",
            "airportName":"临汾乔李",
            "airportPy":"linfenqiaoli",
            "airportPyShort":"lfql"
        },
        {
            "firstLetter":"L",
            "airportCode":"LXI",
            "airportName":"林西",
            "airportPy":"linxi",
            "airportPyShort":"lx"
        },
        {
            "firstLetter":"L",
            "airportCode":"LYI",
            "airportName":"临沂沭埠岭",
            "airportPy":"linyishubuling",
            "airportPyShort":"lysbl"
        },
        {
            "firstLetter":"L",
            "airportCode":"LZY",
            "airportName":"林芝米林",
            "airportPy":"linzhimilin",
            "airportPyShort":"lzml"
        },
        {
            "firstLetter":"L",
            "airportCode":"HZH",
            "airportName":"黎平",
            "airportPy":"liping",
            "airportPyShort":"lp"
        },
        {
            "firstLetter":"L",
            "airportCode":"LPF",
            "airportName":"六盘水月照",
            "airportPy":"liupanshuiyuezhao",
            "airportPyShort":"lpsyz"
        },
        {
            "firstLetter":"L",
            "airportCode":"LZH",
            "airportName":"柳州白莲",
            "airportPy":"liuzhoubailian",
            "airportPyShort":"lzbl"
        },
        {
            "firstLetter":"L",
            "airportCode":"LYA",
            "airportName":"洛阳北郊",
            "airportPy":"luoyangbeijiao",
            "airportPyShort":"lybj"
        },
        {
            "firstLetter":"L",
            "airportCode":"LZO",
            "airportName":"泸州蓝田",
            "airportPy":"luzhoulantian",
            "airportPyShort":"lzlt"
        },
        {
            "firstLetter":"L",
            "airportCode":"LLV",
            "airportName":"吕梁大武",
            "airportPy":"lvliangdawu",
            "airportPyShort":"lldw"
        }
    ],
    "M":[
        {
            "firstLetter":"M",
            "airportCode":"MZG",
            "airportName":"马公",
            "airportPy":"magong",
            "airportPyShort":"mg"
        },
        {
            "firstLetter":"M",
            "airportCode":"LUM",
            "airportName":"芒市",
            "airportPy":"mangshi",
            "airportPyShort":"ms"
        },
        {
            "firstLetter":"M",
            "airportCode":"NZH",
            "airportName":"满洲里西郊",
            "airportPy":"manzhoulixijiao",
            "airportPyShort":"mzlxj"
        },
        {
            "firstLetter":"M",
            "airportCode":"MXZ",
            "airportName":"梅县长岗岌",
            "airportPy":"meixianchanggangji",
            "airportPyShort":"mxcgj"
        },
        {
            "firstLetter":"M",
            "airportCode":"MIG",
            "airportName":"绵阳南郊",
            "airportPy":"mianyangnanjiao",
            "airportPyShort":"mynj"
        },
        {
            "firstLetter":"M",
            "airportCode":"OHE",
            "airportName":"漠河古莲",
            "airportPy":"mohegulian",
            "airportPyShort":"mhgl"
        },
        {
            "firstLetter":"M",
            "airportCode":"MDG",
            "airportName":"牡丹江海浪",
            "airportPy":"mudanjianghailang",
            "airportPyShort":"mdjhl"
        }
    ],
    "N":[
        {
            "firstLetter":"N",
            "airportCode":"NLT",
            "airportName":"那拉提",
            "airportPy":"nalati",
            "airportPyShort":"nlt"
        },
        {
            "firstLetter":"N",
            "airportCode":"KHN",
            "airportName":"南昌昌北",
            "airportPy":"nanchangchangbei",
            "airportPyShort":"nccb"
        },
        {
            "firstLetter":"N",
            "airportCode":"NAO",
            "airportName":"南充高坪",
            "airportPy":"nanchonggaoping",
            "airportPyShort":"ncgp"
        },
        {
            "firstLetter":"N",
            "airportCode":"LZN",
            "airportName":"南竿",
            "airportPy":"nangan",
            "airportPyShort":"ng"
        },
        {
            "firstLetter":"N",
            "airportCode":"NKG",
            "airportName":"南京禄口",
            "airportPy":"nanjinglukou",
            "airportPyShort":"njlk"
        },
        {
            "firstLetter":"N",
            "airportCode":"NNG",
            "airportName":"南宁吴圩",
            "airportPy":"nanningwuwei",
            "airportPyShort":"nnww"
        },
        {
            "firstLetter":"N",
            "airportCode":"YXG",
            "airportName":"南沙永暑礁",
            "airportPy":"nanshayongshujiao",
            "airportPyShort":"nsysj"
        },
        {
            "firstLetter":"N",
            "airportCode":"NTG",
            "airportName":"南通兴东",
            "airportPy":"nantongxingdong",
            "airportPyShort":"ntxd"
        },
        {
            "firstLetter":"N",
            "airportCode":"NNY",
            "airportName":"南阳姜营",
            "airportPy":"nanyangjiangying",
            "airportPyShort":"nyjy"
        },
        {
            "firstLetter":"N",
            "airportCode":"NGB",
            "airportName":"宁波栎社",
            "airportPy":"ningbolishe",
            "airportPyShort":"nbls"
        },
        {
            "firstLetter":"N",
            "airportCode":"NLH",
            "airportName":"宁蒗泸沽湖",
            "airportPy":"ninglangluguhu",
            "airportPyShort":"nllgh"
        }
    ],
    "P":[
        {
            "firstLetter":"P",
            "airportCode":"PZI",
            "airportName":"攀枝花保安营",
            "airportPy":"panzhihuabaoanying",
            "airportPyShort":"pzhbay"
        },
        {
            "firstLetter":"P",
            "airportCode":"PIF",
            "airportName":"屏东",
            "airportPy":"pingdong",
            "airportPyShort":"pd"
        },
        {
            "firstLetter":"P",
            "airportCode":"SYM",
            "airportName":"普洱思茅",
            "airportPy":"puersimao",
            "airportPyShort":"pesm"
        }
    ],
    "Q":[
        {
            "firstLetter":"Q",
            "airportCode":"JIQ",
            "airportName":"黔江武陵山",
            "airportPy":"qianjiangwulingshan",
            "airportPyShort":"qjwls"
        },
        {
            "firstLetter":"Q",
            "airportCode":"IQM",
            "airportName":"且末",
            "airportPy":"qiemo",
            "airportPyShort":"qm"
        },
        {
            "firstLetter":"Q",
            "airportCode":"CMJ",
            "airportName":"七美",
            "airportPy":"qimei",
            "airportPyShort":"qm"
        },
        {
            "firstLetter":"Q",
            "airportCode":"TAO",
            "airportName":"青岛流亭",
            "airportPy":"qingdaoliuting",
            "airportPyShort":"qdlt"
        },
        {
            "firstLetter":"Q",
            "airportCode":"IQN",
            "airportName":"庆阳西峰",
            "airportPy":"qingyangxifeng",
            "airportPyShort":"qyxf"
        },
        {
            "firstLetter":"Q",
            "airportCode":"BPE",
            "airportName":"秦皇岛北戴河",
            "airportPy":"qinhuangdaobeidaihe",
            "airportPyShort":"qhdbdh"
        },
        {
            "firstLetter":"Q",
            "airportCode":"NDG",
            "airportName":"齐齐哈尔三家子",
            "airportPy":"qiqihaersanjiazi",
            "airportPyShort":"qqhesjz"
        },
        {
            "firstLetter":"Q",
            "airportCode":"JJN",
            "airportName":"泉州晋江",
            "airportPy":"quanzhoujinjiang",
            "airportPyShort":"qzjj"
        },
        {
            "firstLetter":"Q",
            "airportCode":"JUZ",
            "airportName":"衢州",
            "airportPy":"quzhou",
            "airportPyShort":"qz"
        }
    ],
    "R":[
        {
            "firstLetter":"R",
            "airportCode":"RKZ",
            "airportName":"日喀则和平",
            "airportPy":"rikazeheping",
            "airportPyShort":"rkzhp"
        },
        {
            "firstLetter":"R",
            "airportCode":"RIZ",
            "airportName":"日照山字河",
            "airportPy":"rizhaoshanzihe",
            "airportPyShort":"rzszh"
        }
    ],
    "S":[
        {
            "firstLetter":"S",
            "airportCode":"SQJ",
            "airportName":"三明沙县",
            "airportPy":"sanmingshaxian",
            "airportPyShort":"smsx"
        },
        {
            "firstLetter":"S",
            "airportCode":"SYX",
            "airportName":"三亚凤凰",
            "airportPy":"sanyafenghuang",
            "airportPyShort":"syfh"
        },
        {
            "firstLetter":"S",
            "airportCode":"PVG,SHA",
            "airportName":"上海",
            "airportPy":"shanghai",
            "airportPyShort":"sh"
        },
        {
            "firstLetter":"S",
            "airportCode":"SHA",
            "airportName":"上海虹桥",
            "airportPy":"shanghaihongqiao",
            "airportPyShort":"shhq"
        },
        {
            "firstLetter":"S",
            "airportCode":"PVG",
            "airportName":"上海浦东",
            "airportPy":"shanghaipudong",
            "airportPyShort":"shpd"
        },
        {
            "firstLetter":"S",
            "airportCode":"SQD",
            "airportName":"上饶三清山",
            "airportPy":"shangraosanqingshan",
            "airportPyShort":"srsqs"
        },
        {
            "firstLetter":"S",
            "airportCode":"KNH",
            "airportName":"尚义",
            "airportPy":"shangyi",
            "airportPyShort":"sy"
        },
        {
            "firstLetter":"S",
            "airportCode":"HSC",
            "airportName":"韶关",
            "airportPy":"shaoguan",
            "airportPyShort":"sg"
        },
        {
            "firstLetter":"S",
            "airportCode":"HPG",
            "airportName":"神农架红坪",
            "airportPy":"shennongjiahongping",
            "airportPyShort":"snjhp"
        },
        {
            "firstLetter":"S",
            "airportCode":"SHE",
            "airportName":"沈阳桃仙",
            "airportPy":"shenyangtaoxian",
            "airportPyShort":"sytx"
        },
        {
            "firstLetter":"S",
            "airportCode":"SZX",
            "airportName":"深圳宝安",
            "airportPy":"shenzhenbaoan",
            "airportPyShort":"szba"
        },
        {
            "firstLetter":"S",
            "airportCode":"SHF",
            "airportName":"石河子花园",
            "airportPy":"shihezihuayuan",
            "airportPyShort":"shzhy"
        },
        {
            "firstLetter":"S",
            "airportCode":"SJW",
            "airportName":"石家庄正定",
            "airportPy":"shijiazhuangzhengding",
            "airportPyShort":"sjzzd"
        },
        {
            "firstLetter":"S",
            "airportCode":"WDS",
            "airportName":"十堰武当山",
            "airportPy":"shiyanwudangshan",
            "airportPyShort":"sywds"
        }
    ],
    "T":[
        {
            "firstLetter":"T",
            "airportCode":"TCG",
            "airportName":"塔城",
            "airportPy":"tacheng",
            "airportPyShort":"tc"
        },
        {
            "firstLetter":"T",
            "airportCode":"TPE,TSA",
            "airportName":"台北",
            "airportPy":"taibei",
            "airportPyShort":"tb"
        },
        {
            "firstLetter":"T",
            "airportCode":"TSA",
            "airportName":"台北松山",
            "airportPy":"taibeisongshan",
            "airportPyShort":"tbss"
        },
        {
            "firstLetter":"T",
            "airportCode":"TPE",
            "airportName":"台北桃园",
            "airportPy":"taibeitaoyuan",
            "airportPyShort":"tbty"
        },
        {
            "firstLetter":"T",
            "airportCode":"TTT",
            "airportName":"台东丰年",
            "airportPy":"taidongfengnian",
            "airportPyShort":"tdfn"
        },
        {
            "firstLetter":"T",
            "airportCode":"TNN",
            "airportName":"台南",
            "airportPy":"tainan",
            "airportPyShort":"tn"
        },
        {
            "firstLetter":"T",
            "airportCode":"TYN",
            "airportName":"太原武宿",
            "airportPy":"taiyuanwusu",
            "airportPyShort":"tyws"
        },
        {
            "firstLetter":"T",
            "airportCode":"TXG",
            "airportName":"台中",
            "airportPy":"taizhong",
            "airportPyShort":"tz"
        },
        {
            "firstLetter":"T",
            "airportCode":"RMQ",
            "airportName":"台中清泉岗",
            "airportPy":"taizhongqingquangang",
            "airportPyShort":"tzqqg"
        },
        {
            "firstLetter":"T",
            "airportCode":"HYN",
            "airportName":"台州路桥",
            "airportPy":"taizhouluqiao",
            "airportPyShort":"tzlq"
        },
        {
            "firstLetter":"T",
            "airportCode":"TVS",
            "airportName":"唐山三女河",
            "airportPy":"tangshansannvhe",
            "airportPyShort":"tssnh"
        },
        {
            "firstLetter":"T",
            "airportCode":"TCZ",
            "airportName":"腾冲驼峰",
            "airportPy":"tengchongtuofeng",
            "airportPyShort":"tctf"
        },
        {
            "firstLetter":"T",
            "airportCode":"TSN",
            "airportName":"天津滨海",
            "airportPy":"tianjinbinhai",
            "airportPyShort":"tjbh"
        },
        {
            "firstLetter":"T",
            "airportCode":"THQ",
            "airportName":"天水麦积山",
            "airportPy":"tianshuimaijishan",
            "airportPyShort":"tsmjs"
        },
        {
            "firstLetter":"T",
            "airportCode":"TNH",
            "airportName":"通化",
            "airportPy":"tonghua",
            "airportPyShort":"th"
        },
        {
            "firstLetter":"T",
            "airportCode":"TGO",
            "airportName":"通辽",
            "airportPy":"tongliao",
            "airportPyShort":"tl"
        },
        {
            "firstLetter":"T",
            "airportCode":"TEN",
            "airportName":"铜仁凤凰",
            "airportPy":"tongrenfenghuang",
            "airportPyShort":"trfh"
        },
        {
            "firstLetter":"T",
            "airportCode":"TLQ",
            "airportName":"吐鲁番交河",
            "airportPy":"tulufanjiaohe",
            "airportPyShort":"tlfjh"
        }
    ],
    "W":[
        {
            "firstLetter":"W",
            "airportCode":"WXN",
            "airportName":"万州五桥",
            "airportPy":"wanzhouwuqiao",
            "airportPyShort":"wzwq"
        },
        {
            "firstLetter":"W",
            "airportCode":"WEF",
            "airportName":"潍坊",
            "airportPy":"weifang",
            "airportPyShort":"wf"
        },
        {
            "firstLetter":"W",
            "airportCode":"WEH",
            "airportName":"威海大水泊",
            "airportPy":"weihaidashuibo",
            "airportPyShort":"whdsb"
        },
        {
            "firstLetter":"W",
            "airportCode":"WNH",
            "airportName":"文山普者黑",
            "airportPy":"wenshanpuzhehei",
            "airportPyShort":"wspzh"
        },
        {
            "firstLetter":"W",
            "airportCode":"WNZ",
            "airportName":"温州龙湾",
            "airportPy":"wenzhoulongwan",
            "airportPyShort":"wzlw"
        },
        {
            "firstLetter":"W",
            "airportCode":"WUA",
            "airportName":"乌海",
            "airportPy":"wuhai",
            "airportPyShort":"wh"
        },
        {
            "firstLetter":"W",
            "airportCode":"WUH",
            "airportName":"武汉天河",
            "airportPy":"wuhantianhe",
            "airportPyShort":"whth"
        },
        {
            "firstLetter":"W",
            "airportCode":"UCB",
            "airportName":"乌兰察布集宁",
            "airportPy":"wulanchabujining",
            "airportPyShort":"wlcbjn"
        },
        {
            "firstLetter":"W",
            "airportCode":"HLH",
            "airportName":"乌兰浩特依勒力特",
            "airportPy":"wulanhaoteyilelite",
            "airportPyShort":"wlhtyllt"
        },
        {
            "firstLetter":"W",
            "airportCode":"URC",
            "airportName":"乌鲁木齐地窝堡",
            "airportPy":"wulumuqidiwobao",
            "airportPyShort":"wlmqdwb"
        },
        {
            "firstLetter":"W",
            "airportCode":"WUX",
            "airportName":"无锡硕放",
            "airportPy":"wuxishuofang",
            "airportPyShort":"wxsf"
        },
        {
            "firstLetter":"W",
            "airportCode":"WUS",
            "airportName":"武夷山",
            "airportPy":"wuyishan",
            "airportPyShort":"wys"
        },
        {
            "firstLetter":"W",
            "airportCode":"WUZ",
            "airportName":"梧州长洲岛",
            "airportPy":"wuzhouchangzhoudao",
            "airportPyShort":"wzczd"
        }
    ],
    "X":[
        {
            "firstLetter":"X",
            "airportCode":"XMN",
            "airportName":"厦门高崎",
            "airportPy":"xiamengaoqi",
            "airportPyShort":"xmgq"
        },
        {
            "firstLetter":"X",
            "airportCode":"HKG",
            "airportName":"香港赤鱲角",
            "airportPy":"xianggangchiliejiao",
            "airportPyShort":"xgclj"
        },
        {
            "firstLetter":"X",
            "airportCode":"XFN",
            "airportName":"襄阳刘集",
            "airportPy":"xiangyangliuji",
            "airportPyShort":"xylj"
        },
        {
            "firstLetter":"X",
            "airportCode":"XIY",
            "airportName":"西安咸阳",
            "airportPy":"xianxianyang",
            "airportPyShort":"xaxy"
        },
        {
            "firstLetter":"X",
            "airportCode":"XIC",
            "airportName":"西昌青山",
            "airportPy":"xichangqingshan",
            "airportPyShort":"xcqs"
        },
        {
            "firstLetter":"X",
            "airportCode":"XIL",
            "airportName":"锡林浩特",
            "airportPy":"xilinhaote",
            "airportPyShort":"xlht"
        },
        {
            "firstLetter":"X",
            "airportCode":"XNT",
            "airportName":"邢台褡裢",
            "airportPy":"xingtaidalian",
            "airportPyShort":"xtdl"
        },
        {
            "firstLetter":"X",
            "airportCode":"ACX",
            "airportName":"兴义万峰林",
            "airportPy":"xingyiwanfenglin",
            "airportPyShort":"xywfl"
        },
        {
            "firstLetter":"X",
            "airportCode":"XNN",
            "airportName":"西宁曹家堡",
            "airportPy":"xiningcaojiabao",
            "airportPyShort":"xncjb"
        },
        {
            "firstLetter":"X",
            "airportCode":"WUT",
            "airportName":"忻州五台山",
            "airportPy":"xinzhouwutaishan",
            "airportPyShort":"xzwts"
        },
        {
            "firstLetter":"X",
            "airportCode":"JHG",
            "airportName":"西双版纳嘎洒",
            "airportPy":"xishuangbannagasa",
            "airportPyShort":"xsbngs"
        },
        {
            "firstLetter":"X",
            "airportCode":"XUZ",
            "airportName":"徐州观音",
            "airportPy":"xuzhouguanyin",
            "airportPyShort":"xzgy"
        }
    ],
    "Y":[
        {
            "firstLetter":"Y",
            "airportCode":"ENY",
            "airportName":"延安二十里铺",
            "airportPy":"yananershilipu",
            "airportPyShort":"yaeslp"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YNZ",
            "airportName":"盐城南洋",
            "airportPy":"yanchengnanyang",
            "airportPyShort":"ycny"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YTY",
            "airportName":"扬州泰州",
            "airportPy":"yangzhoutaizhou",
            "airportPyShort":"yztz"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YNJ",
            "airportName":"延吉朝阳川",
            "airportPy":"yanjichaoyangchuan",
            "airportPyShort":"yjcyc"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YNT",
            "airportName":"烟台蓬莱",
            "airportPy":"yantaipenglai",
            "airportPyShort":"ytpl"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YBP",
            "airportName":"宜宾菜坝",
            "airportPy":"yibincaiba",
            "airportPyShort":"ybcb"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YIH",
            "airportName":"宜昌三峡",
            "airportPy":"yichangsanxia",
            "airportPyShort":"ycsx"
        },
        {
            "firstLetter":"Y",
            "airportCode":"LDS",
            "airportName":"伊春林都",
            "airportPy":"yichunlindu",
            "airportPyShort":"ycld"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YIC",
            "airportName":"宜春明月山",
            "airportPy":"yichunmingyueshan",
            "airportPyShort":"ycmys"
        },
        {
            "firstLetter":"Y",
            "airportCode":"INC",
            "airportName":"银川河东",
            "airportPy":"yinchuanhedong",
            "airportPyShort":"ychd"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YKH",
            "airportName":"营口兰旗",
            "airportPy":"yingkoulanqi",
            "airportPyShort":"yklq"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YIN",
            "airportName":"伊宁",
            "airportPy":"yining",
            "airportPyShort":"yn"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YIW",
            "airportName":"义乌",
            "airportPy":"yiwu",
            "airportPyShort":"yw"
        },
        {
            "firstLetter":"Y",
            "airportCode":"LLF",
            "airportName":"永州零陵",
            "airportPy":"yongzhoulingling",
            "airportPyShort":"yzll"
        },
        {
            "firstLetter":"Y",
            "airportCode":"RHT",
            "airportName":"右旗巴丹吉林",
            "airportPy":"youqibadanjilin",
            "airportPyShort":"yqbdjl"
        },
        {
            "firstLetter":"Y",
            "airportCode":"UYN",
            "airportName":"榆林榆阳",
            "airportPy":"yulinyuyang",
            "airportPyShort":"ylyy"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YCU",
            "airportName":"运城关公",
            "airportPy":"yunchengguangong",
            "airportPyShort":"ycgg"
        },
        {
            "firstLetter":"Y",
            "airportCode":"YUS",
            "airportName":"玉树巴塘",
            "airportPy":"yushubatang",
            "airportPyShort":"ysbt"
        }
    ],
    "Z":[
        {
            "firstLetter":"Z",
            "airportCode":"DYG",
            "airportName":"张家界荷花",
            "airportPy":"zhangjiajiehehua",
            "airportPyShort":"zjjhh"
        },
        {
            "firstLetter":"Z",
            "airportCode":"ZQZ",
            "airportName":"张家口宁远",
            "airportPy":"zhangjiakouningyuan",
            "airportPyShort":"zjkny"
        },
        {
            "firstLetter":"Z",
            "airportCode":"YZY",
            "airportName":"张掖甘州",
            "airportPy":"zhangyeganzhou",
            "airportPyShort":"zygz"
        },
        {
            "firstLetter":"Z",
            "airportCode":"ZHA",
            "airportName":"湛江",
            "airportPy":"zhanjiang",
            "airportPyShort":"zj"
        },
        {
            "firstLetter":"Z",
            "airportCode":"ZAT",
            "airportName":"昭通",
            "airportPy":"zhaotong",
            "airportPyShort":"zt"
        },
        {
            "firstLetter":"Z",
            "airportCode":"CGO",
            "airportName":"郑州新郑",
            "airportPy":"zhengzhouxinzheng",
            "airportPyShort":"zzxz"
        },
        {
            "firstLetter":"Z",
            "airportCode":"ZHY",
            "airportName":"中卫沙坡头",
            "airportPy":"zhongweishapotou",
            "airportPyShort":"zwspt"
        },
        {
            "firstLetter":"Z",
            "airportCode":"HSN",
            "airportName":"舟山普陀山",
            "airportPy":"zhoushanputuoshan",
            "airportPyShort":"zspts"
        },
        {
            "firstLetter":"Z",
            "airportCode":"ZUH",
            "airportName":"珠海金湾",
            "airportPy":"zhuhaijinwan",
            "airportPyShort":"zhjw"
        },
        {
            "firstLetter":"Z",
            "airportCode":"ZYI",
            "airportName":"遵义新舟",
            "airportPy":"zunyixinzhou",
            "airportPyShort":"zyxz"
        },
        {
            "firstLetter":"Z",
            "airportCode":"AXF",
            "airportName":"左旗巴彦浩特",
            "airportPy":"zuoqibayanhaote",
            "airportPyShort":"zqbyht"
        }
    ]
}
}
